site_name: Walter
repo_url: https://github.com/jochenalt/Walter
repo_name: Walter
site_description: Walter a vintage robot Arm 
pages:
    - 'Home - Who is Walter?': 'index.md'
    - 'Construction - How is Walter built?': 'Construction.md'
    - 'Trajectory - How does Walter move?': 'Trajectory.md'
    - 'Kinematics - How to compute angles': 'Kinematics.md'
    - 'Webserver - Who executes trajectories?': 'Webserver.md'
    - 'Cortex - how to control motors': 'Cortex.md'
    - 'Control Cabinet - GBD style': 'Control-Cabinet.md'
    - 'Bill of Material - everyone likes lists': 'Bill-of-Material.md'
    - 'Gallery - Selfies': 'Gallery.md'
